name: Build

on:
  push: ~

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v3
        with:
          go-version: "^1.18"

      - name: Install dependencies
        run: |
          go mod download

      - name: Test
        run: |
          export CLOUD_CONFORMITY_API_KEY="dummy"
          go test -v

      - name: Build
        run: ./build.sh

      - uses: actions/upload-artifact@v3
        with:
          name: builds
          path: build/*
